buildscript {
    ext.kotlin_version = '1.8.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}        uses: actions/upload-artifact@v4
        with:
          name: crowd-express-solver-debug
          path: crowd-express-android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
